"""
add role to users table

Revision ID: 8c2ea235bbdd
Revises: 556df9ab3eef
Create Date: 2025-08-02 16:07:44.573559

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8c2ea235bbdd"
down_revision: str | Sequence[str] | None = "556df9ab3eef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("ADMIN", "DISPATCHER", "COURIER", "CLIENT", name="userroles").create(op.get_bind())
    op.add_column(
        "users",
        sa.Column(
            "role",
            postgresql.ENUM(
                "ADMIN", "DISPATCHER", "COURIER", "CLIENT", name="userroles", create_type=False
            ),
            server_default="ADMIN",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    sa.Enum("ADMIN", "DISPATCHER", "COURIER", "CLIENT", name="userroles").drop(op.get_bind())
    # ### end Alembic commands ###
