"""
add orders table

Revision ID: e51213e259c3
Revises: 8c2ea235bbdd
Create Date: 2025-08-10 19:28:42.964218

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e51213e259c3"
down_revision: str | Sequence[str] | None = "8c2ea235bbdd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "start_point",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "end_point",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("distance_km", sa.Float(), nullable=True),
        sa.Column("duration_minutes", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # Create indices with IF NOT EXISTS protection
    op.execute("CREATE INDEX IF NOT EXISTS idx_orders_end_point ON orders USING gist (end_point);")
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_orders_start_point ON orders USING gist (start_point);"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_orders_start_point", table_name="orders", postgresql_using="gist")
    op.drop_index("idx_orders_end_point", table_name="orders", postgresql_using="gist")
    op.drop_table("orders")
    # ### end Alembic commands ###
